version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - zip -r deployment-package.zip index.js package.json node_modules
artifacts:
  files:
    - deployment-package.zip
